// <auto-generated />
using System;
using ErnyosKozoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErnyosKozoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328092908_AddAdminAndSpotSuggestions")]
    partial class AddAdminAndSpotSuggestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErnyosKozoApi.Models.Bejegyzes", b =>
                {
                    b.Property<int>("BejegyzesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BejegyzesID"));

                    b.Property<string>("Cim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FelhasznaloID")
                        .HasColumnType("int");

                    b.Property<string>("KepUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SpotID")
                        .HasColumnType("int");

                    b.Property<string>("Tartalom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BejegyzesID");

                    b.HasIndex("FelhasznaloID");

                    b.HasIndex("SpotID");

                    b.ToTable("Bejegyzesek");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Felhasznalo", b =>
                {
                    b.Property<int>("FelhasznaloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FelhasznaloID"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelhasznaloNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helyszin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Klub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SzuletesiDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeljesNev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FelhasznaloID");

                    b.ToTable("Felhasznalok");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Hir", b =>
                {
                    b.Property<int>("HirID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HirID"));

                    b.Property<string>("Cim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KepUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tartalom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HirID");

                    b.ToTable("Hirek");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Komment", b =>
                {
                    b.Property<int>("KommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KommentID"));

                    b.Property<int>("BejegyzesID")
                        .HasColumnType("int");

                    b.Property<int>("FelhasznaloID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SzuloKommentID")
                        .HasColumnType("int");

                    b.Property<string>("Tartalom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KommentID");

                    b.HasIndex("BejegyzesID");

                    b.HasIndex("FelhasznaloID");

                    b.HasIndex("SzuloKommentID");

                    b.ToTable("Kommentek");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Kovetes", b =>
                {
                    b.Property<int>("KovetesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KovetesID"));

                    b.Property<int>("KovetettFelhasznaloID")
                        .HasColumnType("int");

                    b.Property<int>("KovetoFelhasznaloID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.HasKey("KovetesID");

                    b.HasIndex("KovetoFelhasznaloID", "KovetettFelhasznaloID")
                        .IsUnique();

                    b.ToTable("Kovetesek");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Spot", b =>
                {
                    b.Property<int>("SpotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpotID"));

                    b.Property<double?>("AtlagSzel")
                        .HasColumnType("float");

                    b.Property<string>("HelyLeiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<int?>("LetrehozoFelhasznaloID")
                        .HasColumnType("int");

                    b.Property<double?>("Lon")
                        .HasColumnType("float");

                    b.Property<int?>("Magassag")
                        .HasColumnType("int");

                    b.Property<string>("Megye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orszag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Szabalyok")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpotID");

                    b.ToTable("Spotok");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.SpotJavaslat", b =>
                {
                    b.Property<int>("SpotJavaslatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpotJavaslatID"));

                    b.Property<string>("AdminMegjegyzes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AtlagSzel")
                        .HasColumnType("float");

                    b.Property<int?>("BekuldoFelhasznaloID")
                        .HasColumnType("int");

                    b.Property<bool>("Feldolgozva")
                        .HasColumnType("bit");

                    b.Property<string>("HelyLeiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Lon")
                        .HasColumnType("float");

                    b.Property<int?>("Magassag")
                        .HasColumnType("int");

                    b.Property<string>("Megye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orszag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Szabalyok")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpotJavaslatID");

                    b.ToTable("SpotJavaslatok");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Utvonal", b =>
                {
                    b.Property<int>("UtvonalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtvonalID"));

                    b.Property<DateTime?>("ErkezesIdo")
                        .HasColumnType("datetime2");

                    b.Property<int>("FelhasznaloID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IndulasIdo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Megjegyzes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpotID")
                        .HasColumnType("int");

                    b.Property<double?>("TavolsagKM")
                        .HasColumnType("float");

                    b.HasKey("UtvonalID");

                    b.ToTable("Utvonalak");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Bejegyzes", b =>
                {
                    b.HasOne("ErnyosKozoApi.Models.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErnyosKozoApi.Models.Spot", "Spot")
                        .WithMany()
                        .HasForeignKey("SpotID");

                    b.Navigation("Felhasznalo");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Komment", b =>
                {
                    b.HasOne("ErnyosKozoApi.Models.Bejegyzes", "Bejegyzes")
                        .WithMany("Kommentek")
                        .HasForeignKey("BejegyzesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErnyosKozoApi.Models.Felhasznalo", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErnyosKozoApi.Models.Komment", "SzuloKomment")
                        .WithMany("Valaszok")
                        .HasForeignKey("SzuloKommentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bejegyzes");

                    b.Navigation("Felhasznalo");

                    b.Navigation("SzuloKomment");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Bejegyzes", b =>
                {
                    b.Navigation("Kommentek");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Komment", b =>
                {
                    b.Navigation("Valaszok");
                });
#pragma warning restore 612, 618
        }
    }
}
