// <auto-generated />
using System;
using ErnyosKozoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErnyosKozoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErnyosKozoApi.Models.Felhasznalo", b =>
                {
                    b.Property<int>("FelhasznaloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FelhasznaloID"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelhasznaloNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Helyszin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Klub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SzuletesiDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeljesNev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FelhasznaloID");

                    b.ToTable("Felhasznalok");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Hir", b =>
                {
                    b.Property<int>("HirID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HirID"));

                    b.Property<string>("Cim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KepUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tartalom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HirID");

                    b.ToTable("Hirek");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Spot", b =>
                {
                    b.Property<int>("SpotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpotID"));

                    b.Property<double?>("AtlagSzel")
                        .HasColumnType("float");

                    b.Property<string>("HelyLeiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Magassag")
                        .HasColumnType("int");

                    b.Property<string>("Megye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orszag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Szabalyok")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpotID");

                    b.ToTable("Spotok");
                });

            modelBuilder.Entity("ErnyosKozoApi.Models.Utvonal", b =>
                {
                    b.Property<int>("UtvonalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtvonalID"));

                    b.Property<DateTime?>("ErkezesIdo")
                        .HasColumnType("datetime2");

                    b.Property<int>("FelhasznaloID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IndulasIdo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Megjegyzes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpotID")
                        .HasColumnType("int");

                    b.Property<double?>("TavolsagKM")
                        .HasColumnType("float");

                    b.HasKey("UtvonalID");

                    b.ToTable("Utvonalak");
                });
#pragma warning restore 612, 618
        }
    }
}
